[book]
authors = ["Sakura"]
language = "en"
multilingual = false
src = "src"
title = "study forever"

[build]
build-dir = "Note"
create-missing = false

[preprocessor.links]

[preprocessor.index]

[output.html]
theme = "my-theme"
default-theme = "light"
preferred-dark-theme = "navy"
curly-quotes = true
mathjax-support = true
copy-fonts = true
# google-analytics = "UA-123456-7"
# additional-css = ["custom.css", "custom2.css"]
# additional-js = ["custom.js"]
no-section-label = false
# git_repository_url = "https://github.com/19979409272/mdbook"
# git-repository-icon = "fa-github"
# site-url = "/study-book/"
# cname = "myproject.rs"
# input-404 = "not-found.md"

[output.html.print]
enable = true

[output.html.fold]
enable = false
level = 0

[output.html.playground]
editable = false
copy-js = true
line-numbers = false

[output.html.search]
enable = true
limit-results = 30
teaser-word-count = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3
copy-js = true
